"""Lightweight Prometheus metrics server with health endpoints.

Provides:
- `/metrics` Prometheus metrics (served by prometheus_client)
- `/healthz` simple liveness JSON
- `/readyz` simple readiness JSON

Modules can import `METRICS` to update counters/gauges.
Start the server with `start_metrics_server()`; it's safe to call multiple times.
"""
from prometheus_client import Counter, Gauge, Histogram, make_wsgi_app
from wsgiref.simple_server import make_server, WSGIServer, WSGIRequestHandler
from typing import Dict, Any
import threading
import json
import os

# ---- Metrics (exported) ----
METRICS: Dict[str, Any] = {}

# Task execution metrics
METRICS["tasks_executed_total"] = Counter("gost_tasks_executed_total", "Total tasks executed by executor")
METRICS["tasks_failed_total"] = Counter("gost_tasks_failed_total", "Total tasks failed")
METRICS["tasks_retried_total"] = Counter("gost_tasks_retried_total", "Total task retries")

# Charts / reports
METRICS["charts_generated_total"] = Counter("gost_charts_generated_total", "Charts generated by main run")

# Notion publisher
METRICS["notion_publish_success_total"] = Counter("gost_notion_publish_success_total", "Notion publish successes")
METRICS["notion_publish_failure_total"] = Counter("gost_notion_publish_failure_total", "Notion publish failures")

# DB errors / retries
METRICS["db_log_errors_total"] = Counter("gost_db_log_errors_total", "DB logging errors encountered")
METRICS["db_log_retries_total"] = Counter("gost_db_log_retries_total", "DB logging retries performed")

# Executor heartbeat / leadership
METRICS["executor_heartbeat_timestamp"] = Gauge("gost_executor_heartbeat_timestamp", "Last executor heartbeat epoch seconds", ["worker_id"])  # label
METRICS["executor_is_leader"] = Gauge("gost_executor_is_leader", "Whether this executor is leader (1 = yes, 0 = no)", ["worker_id"])  # label

# Process / runtime
METRICS["process_uptime_seconds"] = Gauge("gost_process_uptime_seconds", "Process uptime seconds")

# Health gauges
METRICS["liveness"] = Gauge("gost_liveness", "Liveness probe (1 = alive, 0 = dead)")
METRICS["readiness"] = Gauge("gost_readiness", "Readiness probe (1 = ready, 0 = not ready)")

# Internal state
_server_thread = None


def _health_payload() -> Dict[str, Any]:
    payload = {
        "liveness": bool(METRICS["liveness"].collect() and list(METRICS["liveness"].collect())[0].samples[0].value == 1),
        "readiness": bool(METRICS["readiness"].collect() and list(METRICS["readiness"].collect())[0].samples[0].value == 1),
        "env": {"NOTION_API_KEY": bool(os.getenv("NOTION_API_KEY")), "DB_EXISTS": os.path.exists(os.path.join(os.path.dirname(__file__), '..', 'data', 'gold_standard.db'))},
    }
    return payload


def _make_app():
    prometheus_app = make_wsgi_app()

    def app(environ, start_response):
        path = environ.get("PATH_INFO", "")
        if path == "/healthz":
            payload = _health_payload()
            data = json.dumps(payload).encode("utf-8")
            start_response("200 OK", [("Content-Type", "application/json")])
            return [data]
        if path == "/readyz":
            payload = _health_payload()
            status = "200 OK" if payload.get("readiness") else "503 Service Unavailable"
            data = json.dumps(payload).encode("utf-8")
            start_response(status, [("Content-Type", "application/json")])
            return [data]
        # Fallback to Prometheus /metrics and assets
        return prometheus_app(environ, start_response)

    return app


def start_metrics_server(host: str = "0.0.0.0", port: int = None):
    """Start the metrics HTTP server in a daemon thread. Safe to call multiple times."""
    global _server_thread

    if port is None:
        try:
            port = int(os.getenv("METRICS_PORT", "8000"))
        except Exception:
            port = 8000

    if _server_thread and _server_thread.is_alive():
        return

    def _serve():
        try:
            app = _make_app()
            httpd = make_server(host, port, app)
            METRICS["liveness"].set(1)
            METRICS["readiness"].set(1)
            httpd.serve_forever()
        except Exception:
            METRICS["liveness"].set(0)

    t = threading.Thread(target=_serve, daemon=True)
    t.start()
    _server_thread = t


def set_readiness(ready: bool):
    try:
        METRICS["readiness"].set(1 if ready else 0)
    except Exception:
        pass


def set_liveness(alive: bool):
    try:
        METRICS["liveness"].set(1 if alive else 0)
    except Exception:
        pass
